"""location fields

Revision ID: 951f0023c442
Revises: 2ab0605fd5a9
Create Date: 2025-07-11 08:07:36.723920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951f0023c442'
down_revision = '2ab0605fd5a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('place_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('place_id')

    # ### end Alembic commands ###
