"""species

Revision ID: debfc9b4c503
Revises: eaa3670f3cde
Create Date: 2025-04-15 11:20:55.772626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'debfc9b4c503'
down_revision = 'eaa3670f3cde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('species', sa.String(length=100), nullable=True))
        batch_op.drop_column('breed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('breed', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('species')

    # ### end Alembic commands ###
