# Generated by Django 4.2.26 on 2025-11-26 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=50)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True, max_length=1000)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pets/')),
                ('age_years', models.PositiveIntegerField(default=0)),
                ('age_months', models.PositiveIntegerField(default=0)),
                ('weight_lbs', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('male_neutered', 'Male, Neutered'), ('female_spayed', 'Female, Spayed')], max_length=20)),
                ('energy_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High ⚡️')], default='medium', max_length=10)),
                ('temperament', models.CharField(blank=True, choices=[('calm', 'Calm & Gentle'), ('playful', 'Playful & Energetic'), ('friendly', 'Friendly & Social'), ('shy', 'Shy & Cautious'), ('independent', 'Independent'), ('protective', 'Protective')], max_length=20)),
                ('training_level', models.CharField(choices=[('none', 'No Formal Training'), ('basic', 'Basic Commands'), ('advanced', 'Advanced Training'), ('in_training', 'Currently In Training')], default='basic', max_length=20)),
                ('social_preference', models.CharField(choices=[('groups', 'Great in Groups'), ('one_on_one', 'Prefers One-on-One'), ('slow_intro', 'Needs Slow Introductions'), ('selective', 'Selective with Friends')], default='groups', max_length=20)),
                ('good_with_dogs', models.BooleanField(default=True)),
                ('good_with_cats', models.BooleanField(default=False)),
                ('good_with_kids', models.BooleanField(default=True)),
                ('good_with_strangers', models.BooleanField(default=True)),
                ('vaccinations_current', models.BooleanField(default=False)),
                ('microchipped', models.BooleanField(default=False)),
                ('temperament_assessed', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('place_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('available_for_playdate', models.BooleanField(default=True)),
                ('available_for_sitting', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('playdate', 'Playdate Partner'), ('sitter', 'Pet Sitter'), ('walker', 'Dog Walker'), ('other', 'Other')], default='playdate', max_length=20)),
                ('rating', models.PositiveIntegerField(default=5)),
                ('content', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='pets.pet')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='pets.pet')),
            ],
            options={
                'db_table': 'follows',
                'ordering': ['-created_at'],
                'unique_together': {('follower', 'pet')},
            },
        ),
    ]
